#!/usr/bin/env node
export declare const isDir: (name: string) => Promise<boolean>;
export declare const isFile: (name: string) => Promise<boolean>;
export { RollupOptions } from 'rollup';
export { DtsOptions } from './types';
